# Use root/example as user/password credentials
# Inspired by https://github.com/bvda/sw4bed-01/blob/main/examples/lesson-12-persisting-data-with-mongo-db/docker-compose.yaml
# Thanks Brian
version: '3.9'
services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:  
      - 5050:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
